"""priority added in task

Revision ID: 10f70b50eed9
Revises: a70b1806e66b
Create Date: 2025-04-06 23:08:03.544591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f70b50eed9'
down_revision = 'a70b1806e66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_managers', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
